<a href="https://colab.research.google.com/github/fredericokrohling/1-Python-MBA/blob/main/Videoaula_16_Comprehension_com_itera%C3%A7%C3%B5es_em_paralelo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

zip percorre multiplas listas nivelando pela a de menor tamanho. Pode ser combinado com comprehension

In [ ]:
v1=[1,2,3,4,5,6,7,8]
v2=[1,2,3,5,4,6,8,7]

equal_pos=[x if x==y else False for(x,y) in zip(v1,v2)]
print(equal_pos)

[1, 2, 3, False, False, 6, False, False]


In [ ]:
import math as mt

v1=[3,4,5,6,7,8]
v2=[3,5,4,6,8,7,9]

mult_ls = [x*y for(x,y) in zip(v1,v2)]
print(mult_ls)


[9, 20, 20, 36, 56, 56]


In [ ]:
import math as mt

def mult_listas(v1,v2):
  if len(v1)!=len(v2):
    print('Erro: listas com tamanho diferente')
    return mt.nan

  return [x*y for(x,y) in zip(v1,v2)]

In [ ]:
v1=[3,4,5,6,7,8]
v2=[3,5,4,6,8,7,3]

resultado = mult_listas(v1,v2)
print(resultado)

Erro: listas com tamanho diferente
nan


Realizando o produto cartesiano de 2 colecoes


In [ ]:
A = ['a','v']
B = [10,20]

produto = [(x,y) for x in A for y in B]
print('Com comprehension', produto)

Com comprehension [('a', 10), ('a', 20), ('v', 10), ('v', 20)]


In [ ]:
# usando o for
prod_cart = set() # set nao permite repetido, fazendo um pouco diferente aqui. Com o set usamos o add e nao append
for a in A:
  for b in B:
    prod_cart.add((a,b))

print('Com for:', prod_cart)


Com for: {('a', 20), ('a', 10), ('v', 20), ('v', 10)}


In [ ]:
#forma simples de criar listas
l1 = list(range(1,10))
l2 = list(range(0,26,2))
for i,j in zip(l1,l2):
  print(i,j) # vai retornar o primeiro elemento de l1 e o primeiro de l2, depois vai para o segundo e assim sucess.
# vai percorrer ate o ultimo elemento da menor lista

# podemos combinar esse recurso com comprehension





1 0
2 2
3 4
4 6
5 8
6 10
7 12
8 14
9 16


In [ ]:
l1=[1,2,3,4,5,5,6,7]
l2=[1,2,4,6,5,6,3,7]
equal_pos = [x if x==y else False for (x,y) in zip(l1,l2)]
print(equal_pos)

[1, 2, False, False, 5, False, False, 7]


In [ ]:
l1=[2,3,4,5]
l2=[0,5,6,7]
l3 = mult_lst(l1,l2)
print(l3)


[0, 15, 24, 35]


In [ ]:
def mult_lst(l1,l2):
  mult = [x*y for(x,y) in zip(l1,l2)]
  return mult


COMPREHENSIONS ANINHADOS - UMA APLICACAO EH GERAR O PRODUTO CARTESIANO DE 2 COLECOES

lista = [<expressao> for <var_local1> in <objeto1> if <condicao1>
for <var_local2> in <objeto2> if <condicao2>]

Esse resultado e equivalente a:
lista = []

for var_local1 in objeto1:
  if condicao1:
    for var_local2 in objeto2:
      if condicao2:
        lista.append(expressao)
  

Criando a mesma estrutura com um elemento do tipo SET, sem comprehension

prod_cart_for = set()
for a in A:
  for b in B:
    prod_cart_for.add((a,b))
     
    //no set nao usamos o append

In [3]:
# Criar 2 listas dentro de uma lista

lista_listas = [[x for x in range(1,6)] for _ in range(2)]
print(lista_listas)

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]


In [10]:
# Criar 2 listas dentro de uma lista, com um detalhe interessante

lista_listas = [[x*l for x in range(1,6)] for l in range(5)]
print(lista_listas)

SyntaxError: invalid syntax (<ipython-input-10-1e3a8bc06f60>, line 4)

In [17]:
#linda implementacao que eu fiz PARABENS, ficou mais legal que a do professor
import numpy as np
n = 3
pos = 0
linha = np.array([[1 if x == pos else 0 for x in range(n)] for pos in range(3)])
print(linha)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [23]:
# ele fez assim
n = 3
pos = 0
linhas = [[1 if x == pos else 0 for x in range(n)] for pos in range(n)]

#interessante essa forma de imprimir o conteudo
for lin in linhas:
  print(lin)


[1, 0, 0]
[0, 1, 0]
[0, 0, 1]


In [31]:
#exe 2.4 - desafio - resolvi so, TOP!!!!
i= 0
j = 0
n = 3

linhaz = [[i+j*i for j in range(n)] for i in range(n)]

for linb in linhaz:
  print(linb)

[0, 0, 0]
[1, 2, 3]
[2, 4, 6]
